"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class Pose(object):

    __slots__ = ["timestamp", "translation", "rotation"]

    __typenames__ = ["int64_t", "double", "double"]

    __dimensions__ = [None, [3], [4]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.translation = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.rotation = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: double[4] """

    def encode(self):
        buf = BytesIO()
        buf.write(Pose._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>3d', *self.translation[:3]))
        buf.write(struct.pack('>4d', *self.rotation[:4]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Pose._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Pose._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Pose()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.translation = struct.unpack('>3d', buf.read(24))
        self.rotation = struct.unpack('>4d', buf.read(32))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Pose in parents: return 0
        tmphash = (0x4e683ad7b5788352) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Pose._packed_fingerprint is None:
            Pose._packed_fingerprint = struct.pack(">Q", Pose._get_hash_recursive([]))
        return Pose._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Pose._get_packed_fingerprint())[0]

